"""empty message

Revision ID: 89e20b69f737
Revises: None
Create Date: 2016-03-03 05:25:53.104641

"""

# revision identifiers, used by Alembic.
revision = '89e20b69f737'
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=80), nullable=True),
                    sa.Column('last_name', sa.String(length=80), nullable=True),
                    sa.Column('password', sa.String(length=80), nullable=True),
                    sa.Column('nickname', sa.String(length=80), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('nickname')
                    )
    op.create_index(op.f('ix_myprofile_email'), 'myprofile', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_myprofile_email'), table_name='myprofile')
    op.drop_table('myprofile')
    ### end Alembic commands ###
