"""empty message

Revision ID: c27ca3012dcd
Revises: 44a25500b67e
Create Date: 2016-03-03 05:38:49.556469

"""

# revision identifiers, used by Alembic.
revision = 'c27ca3012dcd'
down_revision = '44a25500b67e'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_myprofile_email', table_name='myprofile')
    op.drop_constraint(u'myprofile_nickname_key', 'myprofile', type_='unique')
    op.drop_column('myprofile', 'nickname')
    op.drop_column('myprofile', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('nickname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'myprofile_nickname_key', 'myprofile', ['nickname'])
    op.create_index('ix_myprofile_email', 'myprofile', ['email'], unique=True)
    ### end Alembic commands ###
